name: Build and Publish OCI with Gradle

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      #env: 
      #  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        arguments: bootBuildImage
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to docker
      run: |
        #!/usr/bin/env bash
        docker tag student-api:latest ${{ secrets.DOCKER_USERNAME }}/student-api:latest
        docker images 
        docker push ${{ secrets.DOCKER_USERNAME }}/student-api:latest
